sonar.organization=fiatty
sonar.projectKey=FiatTy_web_local
sonar.projectName=web_local

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/angular-legacy/**,**/assets/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.coverage.exclusions=**/*