sonar.organization=fiatty
sonar.projectKey=web_local
sonar.projectName=web_local

# Source code directory
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Ignore coverage calculation
sonar.coverage.exclusions=**/*

# Tests directory & coverage
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
